name: Email Workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f3003942@ds.study.iitm.ac.in
        run: echo "Email step"

      - name: prime-cache-421d5c5
        run: echo "Prime cache step"
